### ISSUE TITLE
Compatibility with Death Rattle

### ISSUE THREAD

**Issue by Mythos** [Mythos/RimWorld-Diseases-Overhauled#1]
As suggested by Lexplosive the mod "Death Rattle" does also add a coma disease.

**Comment by Mystikvm** [comment]
AFAIK they do not technically conflict. Death Rattle and DO both use a different defName. I don't know if they functionally conflict, as in that one of the mods takes precedence in case they have the same trigger. I don't think triggers are shared, but I am not sure. If not, the only inconsistency is that they're not syntactically equal.

I would advise against removing the Coma disease from DO. Not everyone uses Death Rattle.

**Comment by Mythos** [comment]
Yes I agree, never I thought of removing "our" coma.
Maybe there's a way to merge them somehow.
When I'm in the mood and find some time, I'll find out what death rattle's
coma doing and maybe I'll get some stuff as I'm not so happy with the
current coma.
But I'm not sure if coma == induced coma as the induced coma is a bit weird
to me. Shouldn't increase hunger rate so dramatically IMHO

Mystikvm <notifications@github.com> schrieb am So., 11. Nov. 2018, 22:37:

**Comment by Mystikvm** [comment]
From the mod description: 

Induced coma - pawns can be put in an artificial coma. This may last either two days, five days, fifteen days, thirty days or an unknown duration (between fourty days and more than eighteen years. In their coma, they only need energy for their basal metabolism. So their hungerrate at an induced coma with an unknown duration is reduced to 65%. At shorter durations, the hunger rate is higher. The reason for this lies in an even higher immun response, the shorter the coma duration. This is no natural behaviour. It is (at least in my imagination) brought about by a medication mixture to help pawns, put in a short-term "healing" coma, to fight a severe illness off.

I don't think this is how it medically works. Also, while I like induced coma from an RP-perspective, what does it do other than putting a pawn in a coma? Shouldn't it decrease the severity increase for some diseases? When a pawn is severely ill, you can put them in a coma to slow down disease spreading, or to prevent secondary damage from happening?

**Comment by EPSIL0N** [comment]
I haven't gotten to play outside super short testing periods but the coma may just be to force pawns to stay in bed, a lot of illnesses even in core are difficult to treat if your pawn has reduced blood filtering as they get moody and start mental breaking and leaving the bed. This mod looks like it adds a fair number of illnesses that will injure the blood filtering body parts or do secondary damage where you might not want them away from the bed and rapid treatment.

**Comment by Mythos** [comment]
I just played around with Death Rattle, their coma is completely different from ours.
Also it has a different Hediff name, so in theory it is compatible if people don't mind having 3 different sorts of coma:

* Coma from Death Rattle
* Timed Coma from DO
* Permanent Coma from DO

If there's a way to get the one into the other, I'm very open for a Merge Request as I have no idea right now. 😁 

But the induced coma is completely different and not really connected to the actual coma.
The induced coma should be "as is", as an artificial coma in real life is used to "ease" the pain and / or to slow down metabolism. (AFAIR)

**Comment by Mythos** [comment]
I'm closing this now as there's no real incompatibility between the two mods.
