### ISSUE TITLE
Induced coma hunger rate

### ISSUE THREAD

**Issue by BlueGrrrlPunk** [Mythos/RimWorld-Diseases-Overhauled#40]
Hey so, I noticed the hunger rate when in induced coma is much higher (+90% for the 5 days one) and wondered if it was intended; I changed it for myself by changing the "hungerRateFactorOffset" lines to just "hungerRateFactor" in the hediff, and it does change it to a percentage multplier of x90% instead. If it in fact wasn't intended I hope this helps.

Edit : Same goes for normal Coma

**Comment by Mythos** [comment]
Hey there,

apparently the original author of this mod intended to increase the hunger rate.
See the full README on the front page :-)  (couldn't include it as Steam limits the size of the description)

> Induced coma - pawns can be put in an artificial coma. This may last either two days, five days, fifteen days, thirty days or an unknown duration (between fourty days and more than eighteen years. In their coma, they only need energy for their basal metabolism. So their hungerrate at an induced coma with an unknown duration is reduced to 65%. At shorter durations, the hunger rate is higher. The reason for this lies in an even higher immun response, the shorter the coma duration. This is no natural behaviour. It is (at least in my imagination) brought about by a medication mixture to help pawns, put in a short-term "healing" coma, to fight a severe illness off.

**Comment by BlueGrrrlPunk** [comment]
Ah alright cheers, my bad, didn't see that. Makes sense, thanks for clarifying that.
